
jobs:
  armorcode-validate:
    docker:
      - image: byrnedo/alpine-curl
    environment:
      armorcodehost: https://app.armorcode.com
      product: Juice Shop
      subProduct: JuiceShop- FrontEnd
      environment: Production
      token: $ARMORCODE_TOKEN
      buildTool: CIRCLE_CI
      buildNumber: "<< pipeline.number >>"
      end: 30
    steps:
      - run:
          name: "Armorcode Validate"
          command: |
              token=785a765d-1b0e-4759-99b8-27f17de1e777
              wget https://app.armorcode.com/static/scripts/slastatus.sh
              sh slastatus.sh
workflows:
  armorcode-validation-workflow:
    jobs:
      - armorcode-validate
