name: ArmorCode

env:
  armorcodehost: https://app.armorcode.com
  product: Pet-Clinic
  subProduct: agent
  environment: Production
  token: 785a765d-1b0e-4759-99b8-27f17de1e777
  buildTool: TEAM_CITY
  buildNumber: ${{github.run_number}}
  end: 30
  
on:
  # Triggers the workflow on push request events
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    # ArmorCode Validation Step
    steps:
      - name: ArmorCode Validation
        run: |
          wget https://app.armorcode.com/static/scripts/slastatus.sh
          sh slastatus.sh
