name: ArmorCode

env:
  armorcodehost: https://app.armorcode.com
  product: Demo Release Management
  subProduct: Managed Release Github Actions
  environment: Production
  token: aea7ddeb-9b2e-404f-b3d5-ef62dde148d9
  buildTool: JENKINS
  buildNumber: ${{github.run_number}}
  end: 30
  
on:
  # Triggers the workflow on push request events
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    # ArmorCode Validation Step
    steps:
      - name: ArmorCode Validation
        run: |
          wget https://app.armorcode.com/static/scripts/slastatus.sh
          sh slastatus.sh
